"""create initial tables

Revision ID: 55bd8955f2ba
Revises: 
Create Date: 2026-06-09 23:27:29.397876

为什么迁移脚本要长这样？
- upgrade(): 写"升级"操作（建表、加字段）
- downgrade(): 写"回滚"操作（删表、删字段）
- Alembic 自动生成的内容在 `pass` 的位置，你需要手动补充
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# ============================================================
# Revision 标识（不要改！）
# ============================================================
revision: str = '55bd8955f2ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ============================================================
# 升级操作（alembic upgrade）
# ============================================================
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_type', sa.String(length=10), nullable=False, comment='文件类型：pdf/docx/txt'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（字节）'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='文件存储路径'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='处理状态：uploaded/parsing/chunking/embedding/ready/error'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='失败时的错误信息'),
    sa.Column('meta_data', sa.JSON(), nullable=True, comment='额外元数据（作者、年份等）'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True, comment='会话标题（可以从第一条消息自动生成）'),
    sa.Column('meta_data', sa.JSON(), nullable=True, comment='会话额外信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False, comment='所属文档 ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='文本块内容'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='在文档中的顺序（第几个块）'),
    sa.Column('opensearch_doc_id', sa.String(length=255), nullable=True, comment='OpenSearch 中的文档 ID（向量检索用）'),
    sa.Column('meta_data', sa.JSON(), nullable=True, comment='额外元数据（页码、章节等）'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False, comment='所属会话 ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色：user（用户）或 assistant（AI）'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('sources', sa.JSON(), nullable=True, comment='参考来源（文档片段列表）'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='响应耗时（毫秒）'),
    sa.Column('meta_data', sa.JSON(), nullable=True, comment='额外信息（模型、Token 数等）'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


# ============================================================
# 回滚操作（alembic downgrade）
# ============================================================
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('sessions')
    op.drop_table('documents')
    # ### end Alembic commands ###
